### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by Myphz**
Added list comprehension method at line 12 (also, that line can be outside the for loop, right?)

### CODE REVIEW

**Comment by IrakliMa** [comment]
Shows this error:
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    writer.writerow([list(job.values()) for job in jobs])
ValueError: I/O operation on closed file.
```

**Review by IrakliXYZ — CHANGES_REQUESTED** [review]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    writer.writerow([list(job.values()) for job in jobs])
ValueError: I/O operation on closed file.

**Comment by Myphz** [comment]
OK - that line can't be outside the for loop. It should work now!

**Review by IrakliXYZ — APPROVED** [review]
Indeed :) this works.

**Review by IrakliXYZ — APPROVED** [review]
That's fine.

**Comment by IrakliXYZ** [comment]
Just checked the produced file. Looks like the loop doesn't work as intended. Reverting.

**Pull request merged**
